# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# Ignore failures on nightly Julia
matrix:
  allow_failures:
    - julia: nightly

# We require C++11 compiler for Cxx.jl
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-6
      - g++-6

install:
  # Install specific binutils
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ ! -f $HOME/usr/bin/ld ]; then
      wget https://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.gz;
      tar xzf binutils-2.27.tar.gz;
      (cd binutils-2.27 && ./configure --prefix=$HOME/usr && make && make install);
    fi;
  # Set recent compilers and binutils path
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$HOME/usr/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH=`julia -e 'println(joinpath(Pkg.dir("libTOAST"),"deps","toastpp-2.0.2","linux64","lib"))'`; fi

script:
  # Actually run tests
  - PREBUILT_CI_BINARIES=1 julia -e 'Pkg.clone(pwd()); Pkg.build("libTOAST"); Pkg.test("libTOAST"; coverage=true)'

after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("libTOAST")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("libTOAST")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
