## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# Ignore failures on nightly Julia
matrix:
  allow_failures:
    - julia: nightly

# We require C++11 compiler for Cxx.jl
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-6
      - g++-6
      - binutils
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libgmp-dev
      - libmpfr-dev
      #
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-5
#   env:
#     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

install:
  # Set recent compilers
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
  # Install specific binutils
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ ! -f $HOME/usr/bin/ld ]; then
      wget https://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.gz;
      tar xzf binutils-2.27.tar.gz;
      (cd binutils-2.27 && ./configure --prefix=$HOME/usr && make && make install);
    fi;
  # Actually run tests
  - PREBUILT_CI_BINARIES=1 julia -e 'Pkg.clone(pwd()); Pkg.build("libTOAST"); Pkg.test("libTOAST"; coverage=true)'

after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("libTOAST")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("libTOAST")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
